### ISSUE TITLE
Support for top-level await in ESModule

### ISSUE THREAD

**Issue by DominicRoyStang** [kysely-org/kysely-ctl#118] opened 2024-12-03 22:28 UTC
When the kysely.config.ts file contains top-level await or imports a file that has top-level await, and the package.json `type` field is set to `module`, running `kysely migrate:make <migration name>` errors-out with the following message

>SyntaxError: await is only valid in async functions and the top level bodies of modules

In my case, this top-level await is used to fetch the database password from a secret manager.

Repro repository: https://github.com/DominicRoyStang/kysely-ctl-async-bug

**Comment by igalklebanov** [comment] 2024-12-04 13:40
Hey 👋 

Thanks for raising this and providing a reproduction.

**Comment by igalklebanov** [comment] 2024-12-18 10:49
Try this preview build:

```
npm i https://pkg.pr.new/kysely-org/kysely-ctl@07e409c
```

**Comment by noudadrichem** [comment] 2024-12-20 14:46
Same. The new build works for me!

**Comment by igalklebanov** [comment] 2024-12-21 16:21
Should be resolved in https://github.com/kysely-org/kysely-ctl/releases/tag/v0.10.0.

**Closed by igalklebanov** 2024-12-21 16:21 UTC
Labels: bug
